version: '3.8'

services:
  # Servicio de la API de FastAPI
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # Servicio del Worker para tareas programadas
  worker:
    build: .
    command: python app/worker/scheduler.py
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db

  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432" # Exponer solo si necesitas conectar desde tu máquina local

volumes:
  postgres_data: