services:
  # Servicio de la API de FastAPI
  api:
    build: .
    # El comando ahora es relativo al WORKDIR /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload # <--- CORREGIDO
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  # Servicio del Worker para tareas programadas
  worker:
    build: .
    # El comando ahora es relativo al WORKDIR /app
    command: python -m worker.scheduler  # <--- CORREGIDO
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - db

  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

volumes:
  postgres_data: